version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    container_name: "tns-project-history"
    command: /bin/bash
    ports:
      - "3000:3000"  # アプリケーションポート
      - "9229:9229"  # デバッグポート
    tty: true
    restart: always
