version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      # VSCode拡張機能のキャッシュ用
      - vscode-extensions:/root/.vscode-server/extensions
    tty: true
    command: /bin/bash
    ports:
      - "3000:3000"  # アプリケーションポート
      - "9229:9229"  # デバッグポート

volumes:
  node_modules:
  vscode-extensions:
